/*Copyright (c) 2015-2016 WaveMaker.com All Rights Reserved.
 This software is the confidential and proprietary information of WaveMaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with WaveMaker.com*/

package com.wavemaker.sampleapps.wavekart.eshopping.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.util.HashMap;
import java.util.Map;
import java.util.Collections;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;

import com.wavemaker.runtime.data.model.CustomQuery;
import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;
import com.wavemaker.runtime.data.exception.QueryParameterMismatchException;

@Service
public class EshoppingQueryExecutorServiceImpl implements EshoppingQueryExecutorService {
	private static final Logger LOGGER = LoggerFactory.getLogger(EshoppingQueryExecutorServiceImpl.class);

	@Autowired
	@Qualifier("eshoppingWMQueryExecutor")
	private WMQueryExecutor queryExecutor;

	@Transactional(value = "eshoppingTransactionManager")
	@Override
	public int executeDeleteCartItems_LoggedUser( java.lang.Integer LoggedUserCartId)
	throws QueryParameterMismatchException{
        Map<String, Object> params = new HashMap<String, Object>();
        params.put("LoggedUserCartId", LoggedUserCartId);
        return queryExecutor.executeNamedQueryForUpdate("DeleteCartItems_LoggedUser", params);
	}
	@Transactional(value = "eshoppingTransactionManager")
	@Override
	public Page<Object> executeGet_CartIdByUserid(Pageable pageable)
	throws QueryParameterMismatchException{
        Map<String, Object> params = new HashMap<String, Object>();
        return queryExecutor.executeNamedQuery("Get_CartIdByUserid", params, pageable);
	}
	@Transactional(value = "eshoppingTransactionManager")
	@Override
	public Page<Object> executeGet_CartItems_id(Pageable pageable, java.lang.Integer Cid)
	throws QueryParameterMismatchException{
        Map<String, Object> params = new HashMap<String, Object>();
        params.put("Cid", Cid);
        return queryExecutor.executeNamedQuery("Get_CartItems_id", params, pageable);
	}
	@Transactional(value = "eshoppingTransactionManager")
	@Override
	public Page<Object> executeGetCount_OrderLineItems(Pageable pageable, java.lang.Integer OrderId)
	throws QueryParameterMismatchException{
        Map<String, Object> params = new HashMap<String, Object>();
        params.put("OrderId", OrderId);
        return queryExecutor.executeNamedQuery("GetCount_OrderLineItems", params, pageable);
	}
	@Transactional(value = "eshoppingTransactionManager")
	@Override
	public Page<Object> executeMyCart_Items_Count(Pageable pageable)
	throws QueryParameterMismatchException{
        Map<String, Object> params = new HashMap<String, Object>();
        return queryExecutor.executeNamedQuery("MyCart_Items_Count", params, pageable);
	}
	@Transactional(value = "eshoppingTransactionManager")
	@Override
	public Page<Object> executeTotal_OrderedQty(Pageable pageable, java.lang.Integer orderid)
	throws QueryParameterMismatchException{
        Map<String, Object> params = new HashMap<String, Object>();
        params.put("orderid", orderid);
        return queryExecutor.executeNamedQuery("Total_OrderedQty", params, pageable);
	}
	@Transactional(value = "eshoppingTransactionManager")
	@Override
	public Page<Object> executeTotalItemsPrice_CartProd(Pageable pageable, java.lang.Integer cartId)
	throws QueryParameterMismatchException{
        Map<String, Object> params = new HashMap<String, Object>();
        params.put("cartId", cartId);
        return queryExecutor.executeNamedQuery("TotalItemsPrice_CartProd", params, pageable);
	}
	@Transactional(value = "eshoppingTransactionManager")
	@Override
	public Page<Object> executeTotalPrice_CartProd(Pageable pageable, java.lang.Integer cartid)
	throws QueryParameterMismatchException{
        Map<String, Object> params = new HashMap<String, Object>();
        params.put("cartid", cartid);
        return queryExecutor.executeNamedQuery("TotalPrice_CartProd", params, pageable);
	}
	@Transactional(value = "eshoppingTransactionManager")
	@Override
	public Page<Object> executeTotalPrice_Orders(Pageable pageable, java.lang.Integer Oid)
	throws QueryParameterMismatchException{
        Map<String, Object> params = new HashMap<String, Object>();
        params.put("Oid", Oid);
        return queryExecutor.executeNamedQuery("TotalPrice_Orders", params, pageable);
	}

	@Transactional(value = "eshoppingTransactionManager")
	@Override
	public Page<Object> executeWMCustomQuerySelect(CustomQuery query, Pageable pageable) {
	    return queryExecutor.executeCustomQuery(query, pageable);
	}

	@Transactional(value = "eshoppingTransactionManager")
    @Override
    public int executeWMCustomQueryUpdate(CustomQuery query) {
        return queryExecutor.executeCustomQueryForUpdate(query);
    }
}

